In [1]:
import numpy as np 
import pandas as pd

In [2]:
review_data = pd.read_csv("Restaurant_Reviews.tsv", delimiter="\t")
review_data.head(10)

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1
5     Now I am getting angry and I want my damn pho.      0
6              Honeslty it didn't taste THAT fresh.)      0
7  The potatoes were like rubber and you could te...      0
8                          The fries were great too.      1
9                                     A great touch.      1

In [3]:
review_data.shape

(1000, 2)

In [4]:
review_data.info

<bound method DataFrame.info of                                                 Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]>

In [5]:
review_data.describe()

Liked
count  1000.00000
mean      0.50000
std       0.50025
min       0.00000
25%       0.00000
50%       0.50000
75%       1.00000
max       1.00000

In [6]:
import nltk
import re 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [7]:
data = []
for i in range(0,1000):
    review = re.sub(pattern='[^a-zA-Z]',string = review_data["Review"][i],repl=' ')
    review = review.lower().split()
    review_words = [i for i in review if i not in set(stopwords.words("english"))]
    ps = PorterStemmer()
    review_final = [ps.stem(i) for i in review_words]
    data.append(" ".join(review_final))
len(data)
data[86]

'poor batter meat ratio made chicken tender unsatisfi'

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
a = TfidfVectorizer()
X = a.fit_transform(data).toarray()
Y = review_data['Liked'].values

# Support Vector Machine

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2, random_state=0)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(800, 1565) (200, 1565) (800,) (200,)


In [10]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [11]:
y_pred = svc.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0], dtype=int64)

# Support Vector Machine Accuracy

In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score


svm1 = accuracy_score(y_test, y_pred)
svm2 = precision_score(y_test, y_pred)
svm3 = recall_score(y_test, y_pred)

print(".........Model Score.........")
print("Accuracy Score of the model is ", (svm1 * 100))
print("Precision Score of the model is ", (svm2 * 100))
print("Recall Score of the model is ", (svm3 * 100))


.........Model Score.........
Accuracy Score of the model is  75.5
Precision Score of the model is  82.92682926829268
Recall Score of the model is  66.01941747572816


# Logistic Regression 

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3, random_state=4)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(700, 1565) (300, 1565) (700,) (300,)


In [14]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(x_train,y_train)

LogisticRegression()

In [15]:
y_pred = lg.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1], d

# Logistic Regression Accuracy 

In [16]:
from sklearn.metrics import accuracy_score, precision_score, recall_score


lr1 = accuracy_score(y_test, y_pred)
lr2 = precision_score(y_test, y_pred)
lr3 = recall_score(y_test, y_pred)

print(".........Model Score.........")
print("Accuracy Score of the model is ", (lr1 * 100))
print("Precision Score of the model is ", (lr2 * 100))
print("Recall Score of the model is ", (lr3 * 100))

.........Model Score.........
Accuracy Score of the model is  80.0
Precision Score of the model is  81.06060606060606
Recall Score of the model is  75.35211267605634


# Decision Tree

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.3, random_state=4)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(700, 1565) (300, 1565) (700,) (300,)


In [18]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(x_train,y_train)

DecisionTreeClassifier()

In [19]:
y_pred = DT.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1], d

# Decision Tree Accuracy

In [20]:
from sklearn.metrics import accuracy_score, precision_score, recall_score


dt1 = accuracy_score(y_test, y_pred)
dt2 = precision_score(y_test, y_pred)
dt3 = recall_score(y_test, y_pred)

print(".........Model Score.........")
print("Accuracy Score of the model is ", (dt1 * 100))
print("Precision Score of the model is ", (dt2 * 100))
print("Recall Score of the model is ", (dt3 * 100))

.........Model Score.........
Accuracy Score of the model is  73.66666666666667
Precision Score of the model is  73.33333333333333
Recall Score of the model is  69.71830985915493


In [21]:
variables = ["Model", "Accuracy Score", "Precision Score", "Recall Score"]
values = [
    ["Support Vector Machine", round((svm1*100),2), round((svm2 * 100 ),2) , round((svm3 * 100),2) ],
    ["Logistic Regression", round((lr1 * 100),2), round((lr2 * 100),2), round((lr3 * 100),2)],
    ["Decision Tree", round((dt1 * 100),2), round((dt2 * 100),2), round((dt3 * 100),2)]
]
df = pd.DataFrame(values, columns=variables)
df

Model  Accuracy Score  Precision Score  Recall Score
0  Support Vector Machine           75.50            82.93         66.02
1     Logistic Regression           80.00            81.06         75.35
2           Decision Tree           73.67            73.33         69.72

#### Testing Three models and finding the output of each

In [22]:
# This code is used to preprocess the review which are given by the user 
def PreProcess(txt):
    for i in txt:
        review = re.sub(pattern='[^a-zA-Z]', string=txt, repl=' ')
        review = review.lower().split()
        ps = PorterStemmer()
        review_words = [i for i in review if i not in set(stopwords.words("english"))]
        ps = PorterStemmer()
        review_final = [ps.stem(i) for i in review_words]
        return " ".join(review_final)

In [30]:
review = PreProcess(input("Enter the review : "))
dt_output = DT.predict(a.transform([review]).toarray())
svm_output = svc.predict(a.transform([review]).toarray())
lr_output = lg.predict(a.transform([review]).toarray())
dicti = {
    "Decision Tree " : "Negative" if dt_output[0] == 0 else "Positive" ,
    "Support Vector Machine " : "Negative" if svm_output[0] == 0 else "Positive",
    "Linear Regression "  : "Negative" if lr_output[0] == 0 else "Positive"
}
dicti

Enter the review : The food is bad


{'Decision Tree ': 'Negative',
 'Support Vector Machine ': 'Negative',
 'Linear Regression ': 'Negative'}